name: hermex

services:
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    expose:
      - "50052"
      - "3003"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      GRPC_HOST: 0.0.0.0
      GRPC_PORT: 50052
      METRICS_PORT: 3003
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME:-hermex_admin}
      DB_PASSWORD: ${DB_PASSWORD:-hermex_password}
      DB_NAME: ${DB_NAME:-payments_db}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE:-true}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://hermex_user:hermex_password@rabbitmq:5672}
    networks:
      - hermex-network

networks:
  hermex-network:
    name: hermex-network
    external: true
